# Generated by Django 5.1.6 on 2025-02-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('CI', 'Carnet de Identidad'), ('NIT', 'NIT')], max_length=3)),
                ('nro_documento', models.CharField(max_length=20, unique=True)),
                ('complemento', models.CharField(blank=True, help_text='Complemento del CI (opcional)', max_length=5, null=True)),
                ('departamento_documento', models.CharField(choices=[('LP', 'La Paz'), ('CB', 'Cochabamba'), ('SC', 'Santa Cruz'), ('OR', 'Oruro'), ('PT', 'Potosí'), ('CH', 'Chuquisaca'), ('TJ', 'Tarija'), ('BE', 'Beni'), ('PD', 'Pando')], max_length=2)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
